apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-be
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pr-be
  template:
    metadata:
      labels:
        app: pr-be
    spec:
      containers:
      - name: pr-be
        image: pr-be:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003
        imagePullPolicy: IfNotPresent
